[build]
  functions = "functions"
  publish = "public"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express", "serverless-http", "node-telegram-bot-api", "axios"]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "node server.js"
  targetPort = 5000
  port = 8888
  publish = "public"
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"